CREATE TABLE IF NOT EXISTS USERS
(
  ID          SERIAL PRIMARY KEY,
  USERNAME    VARCHAR(50)  NOT NULL UNIQUE,
  PASSWORD    VARCHAR(100) NOT NULL,
  EMAIL       VARCHAR(100) NOT NULL,
  IS_ADMIN    BOOLEAN      NOT NULL DEFAULT FALSE,
  REGISTER_ON TIMESTAMP WITH TIME ZONE,
  LAST_LOGIN  TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS NODES
(
  ID         SERIAL PRIMARY KEY,
  NODE       VARCHAR(20) UNIQUE,
  CREATED_ON TIMESTAMP WITH TIME ZONE,
  UPDATED_ON TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS POSTS
(
  ID         SERIAL PRIMARY KEY,
  WEIGHT     INTEGER,
  USER_ID    VARCHAR(50)  NOT NULL REFERENCES USERS (id),
  TITLE      VARCHAR(100) NOT NULL UNIQUE,
  CONTENT    TEXT,
  NODE_ID    VARCHAR(50) REFERENCES NODES (id),
  STATUS     VARCHAR(10) DEFAULT 'normal' CONSTRAINT check_status CHECK (status IN ('normal', 'delete', 'other')),
  CREATED_ON TIMESTAMP WITH TIME ZONE,
  UPDATED_ON TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS REPLYS
(
  ID         SERIAL PRIMARY KEY,
  POST       VARCHAR(50) REFERENCES POSTS (id),
  REPLY      TEXT,
  STATUS     VARCHAR(10) DEFAULT 'normal' CONSTRAINT check_status CHECK (status IN ('normal', 'delete', 'good')),
  CREATED_ON TIMESTAMP WITH TIME ZONE,
  UPDATED_ON TIMESTAMP WITH TIME ZONE
);