CREATE TABLE IF NOT EXISTS USERS
(
  ID          SERIAL PRIMARY KEY,
  USERNAME    VARCHAR(50)  NOT NULL UNIQUE,
  PASSWORD    VARCHAR(100) NOT NULL,
  EMAIL       VARCHAR(100) NOT NULL,
  IS_ADMIN    BOOLEAN      NOT NULL DEFAULT FALSE,
  ALIVE       VARCHAR(20)  NOT NULL DEFAULT 'normal' CONSTRAINT check_alive CHECK (ALIVE IN
                                                                                   ('normal', 'delece', 'lock', 'other')),
  OTHER       VARCHAR(20),
  REGISTER_ON TIMESTAMP WITHOUT TIME ZONE ,
  LAST_LOGIN  TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS NODES
(
  ID         SERIAL PRIMARY KEY,
  NODE       VARCHAR(20) UNIQUE,
  STATUS     VARCHAR(20) DEFAULT 'normal' CONSTRAINT check_status CHECK (STATUS IN ('normal', 'delete', 'other')),
  OTHER      VARCHAR(20),
  CREATED_ON TIMESTAMP WITHOUT TIME ZONE,
  UPDATED_ON TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS POSTS
(
  ID         SERIAL PRIMARY KEY,
  WEIGHT     INTEGER,
  USER_ID    VARCHAR(50)  NOT NULL REFERENCES USERS (id),
  TITLE      VARCHAR(100) NOT NULL UNIQUE,
  CONTENT    TEXT,
  NODE_ID    VARCHAR(50) REFERENCES NODES (id),
  STATUS     VARCHAR(10) DEFAULT 'normal' CONSTRAINT check_status CHECK (STATUS IN ('normal', 'delete', 'other')),
  OTHER      VARCHAR(20),
  CREATED_ON TIMESTAMP WITHOUT TIME ZONE,
  UPDATED_ON TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS REPLYS
(
  ID         SERIAL PRIMARY KEY,
  POST_ID    VARCHAR(50) REFERENCES POSTS (id),
  REPLY      TEXT,
  STATUS     VARCHAR(10) DEFAULT 'normal' CONSTRAINT check_status CHECK (STATUS IN ('normal', 'delete', 'good','other')),
  OTHER      VARCHAR(20),
  CREATED_ON TIMESTAMP WITHOUT TIME ZONE,
  UPDATED_ON TIMESTAMP WITHOUT TIME ZONE
);